version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_server
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  chatbot_api:
    build: .
    container_name: chatbot_api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=your_google_api_key
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: ["uvicorn", "chatbot_api:app", "--host", "0.0.0.0", "--port", "8000"]
